version: 2
updates:
  - directory: /
    open-pull-requests-limit: 5
    package-ecosystem: "github-actions"
    reviewers:
      - "TUDOCK/devops"
    schedule:
      interval: daily
      timezone: "Europe/Berlin"
